# Copyright 2020-2023 The MathWorks, Inc.

# Workflow that contains jobs to test MATLAB Jupyter Integration
name: Testing MATLAB Jupyter Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  call-unit-tests:
    # Runs unit tests
    uses: ./.github/workflows/run-unit-tests.yml
    secrets: inherit

  call-integration-tests:
    # Runs integration tests
    uses: ./.github/workflows/run-integration-tests.yml
    secrets: inherit

  call-e2e-tests:
    # Runs the end-to-end tests
    uses: ./.github/workflows/run-e2e-tests.yml
    secrets: inherit